//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpilationProject8.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epilation
    {
        public int Id { get; set; }
        public string Име_на_пациент { get; set; }
        public string Дата_РЪЦЕ { get; set; }
        public string Дата_ГЛАВА { get; set; }
        public string Дата_КРАКА { get; set; }
        public string Дата_ИНТИМ { get; set; }
    }
}
